### ISSUE TITLE
addDir Error: EISDIR  

### ISSUE THREAD

**Issue by reutopiaer** [floatdrop/gulp-watch#147]
var gulp = require('gulp'),
  watch = require('gulp-watch');
gulp.task('watch', function() {
  watch(__dirname, {events:['addDir']},function (event) {
    console.log('addDir');
  });
});
#gulp watch
[23:25:20] Using gulpfile /I/gulpfile.js
[23:25:20] Starting 'watch'...
[23:25:20] Finished 'watch' after 4.08 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EISDIR, read
    at Error (native)

**Comment by floatdrop** [comment]
Update `gulp-watch` - EISDIR was fixed in 6eafcfc10ab139c49e55cc5fc1669cff93d8c5b3.

**Comment by johnhamm** [comment]
This may have been fixed in a prior release, but the code that fixed it was removed.  Simple fix though.  Just change line 101 in index.js to:
`        if (event === 'unlink' || event === 'unlinkDir'  || event === 'addDir') {`

**Comment by UltCombo** [comment]
@johnhamm I believe you mean line [114 in d24fdecc9a3dd7e54067fb1622019438d696e556](https://github.com/floatdrop/gulp-watch/blob/d24fdecc9a3dd7e54067fb1622019438d696e556/index.js#L114)?
Sorry, but I'm not sure what you mean. That check is to prevent reading files that no longer exist—it has nothing to do with `addDir`, as far as I can see.
We delegate vinyl file creation to the [`vinyl` package](https://github.com/gulpjs/vinyl). Vinyl files can represent both files and directories, being that the latter has the `contents` property set to `null`.

If you facing an error, please create a new issue and provide the necessary steps to reproduce it.

**Comment by zcmk123** [comment]
in current version of gulp-watch, this issue still exist, plz fix it

(node:50240) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read

(node:50240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:50240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
